### ISSUE TITLE
Provide some minimum documentation

### ISSUE THREAD

**Issue by dschien** [home-assistant-libs/zwave-js-server-python#128]
Hi,

this project looks great. After having played around with zwavejs2mqtt I'm really excited about this. However, as a newbie I am not sure how to use this at all.

The minimum example at the bottom of the readme file leaves me confused.

It would be great if there was a minium end-to-end example. I searched for `start_listening` in `node-zwave-js` but without any code occurrences. And there is nothing on stackoverflow on `zwave-js-server-python`.

Much appreciated
Dan

**Comment by cgarwood** [comment]
This library interacts with https://github.com/zwave-js/zwave-js-server (that's where you'll find the start_listening command, etc)

**Comment by dschien** [comment]
Thanks! Much appreciated. I can now see, it's clearly stated in the README. Sorry, lots to take in. Okay, I'll have a look at that. Cheers

**Comment by dschien** [comment]
It would be great if you had suggestions how to wrap the code example in the README.md in a python client file. All this async is new to me. What is a good structure for a client that keeps listening for events until the user interrupts?

**Comment by MartinHjelmare** [comment]
There's a client in the library. Look at the `__main__.py` module for examples how to use the client.

**Comment by dschien** [comment]
Many thanks for the pointer. Looks great. Will have a play.
