### ISSUE TITLE
Protect against value type mismatches

### ISSUE THREAD

**Issue by kpine** [home-assistant-libs/zwave-js-server-python#130]
In some cases, a value ID with a specific type will have a value that does not match the type. For example:
```json
                        {
                            "endpoint": 0,
                            "commandClass": 38,
                            "commandClassName": "Multilevel Switch",
                            "property": "currentValue",
                            "propertyName": "currentValue",
                            "ccVersion": 3,
                            "metadata": {
                                "type": "number",
                                "readable": true,
                                "writeable": false,
                                "min": 0,
                                "max": 99,
                                "label": "Current value"
                            },
                            "value": "unknown"
                        },
```
This is a `"number"` type, but Instead of a valid value in the range 0 to 99, the value is the string `"unknown"`. Unknown is a valid value reported by devices, so node-zwave-js just sets it as a string.

It might make more sense for this value to be converted to `None` in the library, so the HA components don't need to anything special besides check for None (which most do already).

I don't know if there are any other strings besides "unknown" that could be returned for a number, or if this is it.

See these HA issues for examples and dump files related to this problem:
* https://github.com/home-assistant/core/issues/46263
* https://github.com/home-assistant/core/issues/46658
* https://github.com/home-assistant/core/issues/46294

**Comment by marcelveldt** [comment]
This was fixed with #129 and will be in next release.
