### ISSUE TITLE
Migrate to zwave-js 7.0.0

### ISSUE THREAD

**Issue by MartinHjelmare** [home-assistant-libs/zwave-js-server-python#162]
This issue lists changes that are required to support zwave-js 7.0.0.

- The changes require a new schema version, so we can't release any of these changes unless we bump the schema version.
- Of course, we need to coordinate the changes between server and client libraries. Most changes require a change in both libraries.

## Rename controller method

- [ ] Rename controller.removeNodeFromAllAssocations to controller.removeNodeFromAllAssociations.
  https://github.com/zwave-js/zwave-js-server/blob/e0d5dec1a66283f68e044d4beb87e3610a884bb6/src/lib/controller/command.ts#L17
  https://github.com/zwave-js/zwave-js-server/blob/e0d5dec1a66283f68e044d4beb87e3610a884bb6/src/lib/controller/incoming_message.ts#L99-L121
  https://github.com/zwave-js/zwave-js-server/blob/e0d5dec1a66283f68e044d4beb87e3610a884bb6/src/lib/controller/message_handler.ts#L98-L99
  https://github.com/zwave-js/zwave-js-server/blob/e0d5dec1a66283f68e044d4beb87e3610a884bb6/src/lib/controller/outgoing_message.ts#L24
  https://github.com/home-assistant-libs/zwave-js-server-python/blob/876ef9226d1a19d36aa669cb8553dcf8c2b34a6d/zwave_js_server/model/controller.py#L321-L328

## Rework node properties

- [ ] Change isFrequentListening to have the type FLiRS = false | "250ms" | "1000ms" (previously boolean) to indicate the wakeup frequency.
  https://github.com/zwave-js/zwave-js-server/blob/e0d5dec1a66283f68e044d4beb87e3610a884bb6/src/lib/state.ts#L83
  https://github.com/zwave-js/zwave-js-server/blob/e0d5dec1a66283f68e044d4beb87e3610a884bb6/src/lib/state.ts#L177
  https://github.com/home-assistant-libs/zwave-js-server-python/blob/876ef9226d1a19d36aa669cb8553dcf8c2b34a6d/zwave_js_server/model/node.py#L53
  https://github.com/home-assistant-libs/zwave-js-server-python/blob/876ef9226d1a19d36aa669cb8553dcf8c2b34a6d/zwave_js_server/model/node.py#L158-L161
- [ ] Rename maxBaudRate to maxDataRate.
  https://github.com/zwave-js/zwave-js-server/blob/e0d5dec1a66283f68e044d4beb87e3610a884bb6/src/lib/state.ts#L85
  https://github.com/zwave-js/zwave-js-server/blob/e0d5dec1a66283f68e044d4beb87e3610a884bb6/src/lib/state.ts#L179
  https://github.com/home-assistant-libs/zwave-js-server-python/blob/876ef9226d1a19d36aa669cb8553dcf8c2b34a6d/zwave_js_server/model/node.py#L55
  https://github.com/home-assistant-libs/zwave-js-server-python/blob/876ef9226d1a19d36aa669cb8553dcf8c2b34a6d/zwave_js_server/model/node.py#L168-L171
- [ ] Add the node property supportedDataRates to provide an array of supported data rates.
- [ ] Rename the version property to protocolVersion and change its type from number to the enum ProtocolVersion (the underlying values are still the same).
  https://github.com/zwave-js/zwave-js-server/blob/e0d5dec1a66283f68e044d4beb87e3610a884bb6/src/lib/state.ts#L87
  https://github.com/zwave-js/zwave-js-server/blob/e0d5dec1a66283f68e044d4beb87e3610a884bb6/src/lib/state.ts#L181
  https://github.com/home-assistant-libs/zwave-js-server-python/blob/876ef9226d1a19d36aa669cb8553dcf8c2b34a6d/zwave_js_server/model/node.py#L58
  https://github.com/home-assistant-libs/zwave-js-server-python/blob/876ef9226d1a19d36aa669cb8553dcf8c2b34a6d/zwave_js_server/model/node.py#L178-L181
- [ ] Rename the isBeaming property to supportsBeaming to better show its intent.
  https://github.com/zwave-js/zwave-js-server/blob/e0d5dec1a66283f68e044d4beb87e3610a884bb6/src/lib/state.ts#L88
  https://github.com/zwave-js/zwave-js-server/blob/e0d5dec1a66283f68e044d4beb87e3610a884bb6/src/lib/state.ts#L182
  https://github.com/home-assistant-libs/zwave-js-server-python/blob/876ef9226d1a19d36aa669cb8553dcf8c2b34a6d/zwave_js_server/model/node.py#L57
  https://github.com/home-assistant-libs/zwave-js-server-python/blob/876ef9226d1a19d36aa669cb8553dcf8c2b34a6d/zwave_js_server/model/node.py#L183-L186
- [ ] Add the node  property supportsSecurity which is split off from the isSecure property because they have a different meaning.
- [ ] Rename the old nodeType and roleType properties to zwavePlusNodeType and zwavePlusRoleType to clarify that they refer to Z-Wave+.
  https://github.com/zwave-js/zwave-js-server/blob/e0d5dec1a66283f68e044d4beb87e3610a884bb6/src/lib/state.ts#L94
  https://github.com/zwave-js/zwave-js-server/blob/e0d5dec1a66283f68e044d4beb87e3610a884bb6/src/lib/state.ts#L188
  https://github.com/home-assistant-libs/zwave-js-server-python/blob/876ef9226d1a19d36aa669cb8553dcf8c2b34a6d/zwave_js_server/model/node.py#L50
  https://github.com/home-assistant-libs/zwave-js-server-python/blob/876ef9226d1a19d36aa669cb8553dcf8c2b34a6d/zwave_js_server/model/node.py#L213-L216
  https://github.com/zwave-js/zwave-js-server/blob/e0d5dec1a66283f68e044d4beb87e3610a884bb6/src/lib/state.ts#L95
  https://github.com/zwave-js/zwave-js-server/blob/e0d5dec1a66283f68e044d4beb87e3610a884bb6/src/lib/state.ts#L189
  https://github.com/home-assistant-libs/zwave-js-server-python/blob/876ef9226d1a19d36aa669cb8553dcf8c2b34a6d/zwave_js_server/model/node.py#L51
  https://github.com/home-assistant-libs/zwave-js-server-python/blob/876ef9226d1a19d36aa669cb8553dcf8c2b34a6d/zwave_js_server/model/node.py#L218-L221

## Rework node notification event

- [ ] Rework the node notification event and decouple it from the Notification CC. The event callback now indicates which CC raised the event and its arguments are moved into a single object parameter. See https://github.com/zwave-js/node-zwave-js/blob/v7.0.0-beta.1/docs/api/node.md#notification for details.

## Change (check) log level return type

- [ ] Numeric loglevels are converted to the corresponding string loglevel internally. driver.getLogConfig always returns the string loglevel regardless. Check if we need to update the enum in the client.
  https://github.com/home-assistant-libs/zwave-js-server-python/blob/876ef9226d1a19d36aa669cb8553dcf8c2b34a6d/zwave_js_server/const.py#L14-L25

**Comment by raman325** [comment]
all of this should be handled in the linked PR
