### ISSUE TITLE
Add all platforms to Home Assistant

### ISSUE THREAD

**Issue by MartinHjelmare** [home-assistant-libs/zwave-js-server-python#34]
List the platforms we have done and left to do:
- [x] binary sensor https://github.com/home-assistant/core/pull/45081
- [x] climate https://github.com/home-assistant/core/pull/45177
- [x] cover https://github.com/home-assistant/core/pull/45193
- [x] fan
- [x] light
- [x] lock https://github.com/home-assistant/core/pull/45175
- [x] sensor
- [x] switch

Please add a comment if you have started working on a platform.

**Comment by MartinHjelmare** [comment]
Switch is in progress.

**Comment by cgarwood** [comment]
@marcelveldt was working on binary sensor

**Comment by raman325** [comment]
Thanks for adding my PRs didn't see this issue

**Comment by marcelveldt** [comment]
I'm looking into service calls and device/scene events.

**Comment by raman325** [comment]
I'm going to tackle lock services next

**Comment by raman325** [comment]
lock services are awaiting #55 and a release

**Comment by MartinHjelmare** [comment]
Let's close this now. We can track further platform improvements in other issues.
