### ISSUE TITLE
How to ease migration to Z-Wave JS

### ISSUE THREAD

**Issue by MartinHjelmare** [home-assistant-libs/zwave-js-server-python#35]
## Scope

Issue to track ideas and problems for helping users migrate to Z-Wave JS from the other two older Z-Wave integrations in Home Assistant.

- Please add your input in a new comment and we'll update the top post with important information.

## Known facts

- Value id:s used in the integration entity unique_id are different between the 3 integrations, so we won't be able to use those. Entities can be matched using command class and endpoint/index values.
- Battery nodes won't be picked up by z-wave js until they wake up for the first time after the migration (`ozw` would have had the same issue moving from `zwave`)
- Command class support is different between the 3 integrations so some entities may not port over, or new entities will be discovered

**Comment by cgarwood** [comment]
- value id's used in the integration unique_id are different between the 3 integrations, so we won't be able to use those. We'll have to match entities to command class and endpoint/index values.
- battery nodes won't be picked up by z-wave js until they wake up for the first time after the migration (`ozw` would have had the same issue moving from `zwave`)
- command class support is different between the 3 integrations so some entities may not port over, or new entities will be discovered

Thinking out loud, maybe we go through all the entities for the "old" integration we're migrating from, and dump the entity_id, unique_id, node id, command_class, instance/endpoint, and index numbers into a migration file, and then as zwave_js discovers entities/values it looks them up in that file to see if it can find a match?

**Comment by balloob** [comment]
I think that's a great idea. And in the meanwhile we don't delete the old config entry but instead disable it.

**Comment by Mike-Allen** [comment]
Would that work with multiple identical devices from the same manufacturer? 

For devices that can't be auto matched, how about displaying a page that shows all of the entities for the device, including their state? If the device is a switch or a light then have buttons that can turn the device on and off.

Then have a dropdown or listbox filled with the old zwave devices that haven't been assigned. The user can test the unknown device to verify which device it actually is and then select its previous settings from the dropdown and apply it to the unknown device.

Of course the two devices would need to be compared to make sure they each had the same number of entities. Having buttons to refresh, test and/or heal the unknown device on the page would be helpful when all of the attributes for an unknown device weren't found.

Ideally it would be nice to be able to postpone the matching of devices to previous settings and then pick it back up later.

I know this is a lot of work. Perhaps the page could be also used of other zwave purposes. Perhaps for debugging.

Sadly I have no time to write any code so this is only a suggestion. And please ignore my ignorance of the correct names for things above.

**Comment by cgarwood** [comment]
> Would that work with multiple identical devices from the same manufacturer?

Node IDs stay the same and each device would have a unique node ID

**Comment by cgarwood** [comment]
We'll want to make sure we account for people running multiple instances of ozwdaemon so we only migrate entities belonging to the correct instance and don't unload the config entry completely if there are more instances

**Comment by Mike-Allen** [comment]
I knew that zwave devices don't have unique identifiers. I wasn't sure if the Node IDs would remain the same.

Thanks for the work you are doing.

**Comment by SeraphimSerapis** [comment]
How about a semi-manual migration that lets people match the "new" device with one of their old `zwave` devices of the same type.

Clearly this could be a bit tedious with tens of devices but would make sure people can name their devices and entities in the process, too. As this would be a one-time undertaking, a migration wizard wouldn't be too terrible.

**Comment by Mike-Allen** [comment]
Well, not as tedious as manually editing entity ids when one's zwave system gets confused.

I don't know if it would be possible to use a wizard to rebuild a broken zwave system. Perhaps if one could save their zwave devices and entities and then use them to fix a broken zwave system using the wizard. Node IDs can change if one needs to reset a zwave device to get it working again.

I also don't know if using snapshots and restoring from a snapshot makes zwave repair seamless. I've been running HA Core so I don't know how other setups work.

**Comment by skynet01** [comment]
> How about a semi-manual migration that lets people match the "new" device with one of their old `zwave` devices of the same type.
> 
> Clearly this could be a bit tedious with tens of devices but would make sure people can name their devices and entities in the process, too. As this would be a one-time undertaking, a migration wizard wouldn't be too terrible.

I think this is a great v1 solution. If there is an easy UI to match devices/entities between each other it can make the process fairly fast as we can do simple things like auto prefilling the name etc. Followed by a list of items that didn't match. I have 59 devices which mean ill have to rename 259 entities.

**Comment by Madelaide** [comment]
I have just installed ZW JS ( Awesome job to the team, as OZW is dead, long live the ZWJS) and I have around 100 nodes to bring over.

I use the Device>Cog and just rename the device and it renames all the Device's entities, it's pretty efficient and I keep a separate spreadsheet with all the node ids and their name and location, so it's a copy paste and done.

Sometimes I need to manually remove the trailing _3 / _2 appended to some attributes but that's only an evening's work.

So glad to have the stop button on covers now!

The ONLY issue i have is I used to be able to "rescan node" with the OZW Admin tool to bring in missing attributes that were missed on start up, but I can't see how to do this with ZWJS

**Comment by GirzzlyAK** [comment]
>     * Command class support is different between the 3 integrations so some entities may not port over, or new entities will be discovered

I don't know how Command Classes evolve in ZW, but I recognize that some of my devices work currently under the zwave 1.4 integration because they support backward compatibility to that version of CCs (like Alarm CC). I'm curious why all three implementations have differing support for CCs, unless you mean that all the CCs that _are_ supported in each are the same, it's just that some CCs are missing in some integrations.

I'm wondering if it is possible, feasible, or even _smart_, to include the older CCs in the new integration to ease the bridge from zwave 1.4. Not having some of the v1.4 CCs would likely require a lot of changes to sensors and automations, in addition to the entity naming differences, while providing a path forward with the new (to v1.4 folks anyway) CCs as devices are added.

**Comment by skynet01** [comment]
I hope that Command Class is still supported as I rely on this a lot in 1.4 :)

**Comment by MartinHjelmare** [comment]
We have no control of Command Classes. We just consume what each library provides. We can't create Command Classes that are missing in one or the other Z-Wave implementations.

**Comment by GirzzlyAK** [comment]
> We just consume what each library provides.

That makes sense. So at the moment, you rely on what is offered by OpenZWave or ZWave-JS, and on them to include the CCs equally and, hopefully, completely with time. Do you know if these libraries include the older CCs for backward compatibility? I would think they would, given the number of devices out there in-place (like in-wall light switches) that may not be upgradeable to the latest FW.

Here's an example to illustrate my fear. I'm using the zwave 1.4 integration, and my devices use the CCs supported by it, which my automations, Lovelace UI, sensors, and anything else using those entities, also reference. If the new integration comes along and ignores those CCs in preference to the latest CCs, and provide _**only**_ those new entities to HA, then it is a major breaking change to the entire HA environment beyond renaming entities, but also in automation/script logic. This is all based upon my current understanding of ZWave, which is still pretty limited, so may be moot. I just wanted to throw it out there.

**Comment by raman325** [comment]
> I think that's a great idea. And in the meanwhile we don't delete the old config entry but instead disable it.

Will disabling the config entry free up the entity IDs? Or do we have to rename those before we disable?

**Comment by firstof9** [comment]
I am quite sure you have to rename them before you disable.

**Comment by raman325** [comment]
I just looked at the ozw code and it looks like the entities get removed before they get migrated, so no issues with naming conflicts as long as we use the same approach.
