### ISSUE TITLE
Add (major) version check for Zwave JS

### ISSUE THREAD

**Issue by marcelveldt** [home-assistant-libs/zwave-js-server-python#5]
New versions of upstream Zwave JS can possibly contain breaking changes in the API/definitions.
If the zwave server is hosted by the user itself (or in another application like zwave2mqtt) we have no control if the python lib is 100% compatible with the Zwave jS version.

Suggestion is that we add a major-version check in the code of the library and halt (or log) if the major version is not compatible. 

This depends on a PR for Zwave JS to include the version.

**Comment by balloob** [comment]
The version of Z-Wave JS Server is now available and this issue is no longer blocked. Version is received on this line:

https://github.com/home-assistant-libs/zwave-js-server-python/blob/57bfb0cf7a2bb5b8960be20ebd94b59969c58c1d/zwave_js_server/client.py#L250-L259
