### ISSUE TITLE
Todos to finish before Home Assistant Core 2021.2.0b0

### ISSUE THREAD

**Issue by MartinHjelmare** [home-assistant-libs/zwave-js-server-python#53]
Beta 0 will be released on January 27, 2021.

- [ ] Fix light platform.
- [x] https://github.com/home-assistant/core/issues/45284
- [x] https://github.com/home-assistant/core/issues/45272
- [x] Release add/remove node frontend part. https://github.com/home-assistant/frontend/pull/8174
- [x] Update docs with recommended (for now) way to run the node server.
- [x] Add add-on management in config flow.
- [x] Release add-on.

**Comment by kpine** [comment]
Handling of "value notification" events. These are used for central scene events, as well as Basic Set events for some configured devices.

**Comment by marcelveldt** [comment]
> Handling of "value notification" events. These are used for central scene events, as well as Basic Set events for some configured devices.

I'm working on those. Expect the PR to be ready today or tomorrow

**Comment by kpine** [comment]
> 
> 
> > Handling of "value notification" events. These are used for central scene events, as well as Basic Set events for some configured devices.
> 
> I'm working on those. Expect the PR to be ready today or tomorrow

Great. Do you already have event data for Basic Sets? If not, here's a sample.

```
2021-01-19 18:52:24 DEBUG (MainThread) [zwave_js_server] Received message:
{'event': {'args': {'commandClass': 32,
                    'commandClassName': 'Basic',
                    'endpoint': 0,
                    'property': 'event',
                    'propertyName': 'event',
                    'value': 255},
           'event': 'value notification',
           'nodeId': 3,
           'source': 'node'},
 'type': 'event'}

2021-01-19 18:52:27 DEBUG (MainThread) [zwave_js_server] Received message:
{'event': {'args': {'commandClass': 32,
                    'commandClassName': 'Basic',
                    'endpoint': 0,
                    'property': 'event',
                    'propertyName': 'event',
                    'value': 0},
           'event': 'value notification',
           'nodeId': 3,
           'source': 'node'},
 'type': 'event'}
```

**Comment by kpine** [comment]
Central Scene.
```
{
  "type": "event",
  "event": {
    "source": "node",
    "event": "value notification",
    "nodeId": 11,
    "args": {
      "commandClassName": "Central Scene",
      "commandClass": 91,
      "property": "scene",
      "propertyKey": "001",
      "value": 6,
      "propertyName": "scene",
      "propertyKeyName": "001"
    }
  }
```

**Comment by marcelveldt** [comment]
@MartinHjelmare what to do here ?

1) Just pass the complete event dict as shown above to HA eventbus.
2) Create a new model NotificationValue in the library as dataclass so we can easily do to/from dict.
3) Use the existing Value class (as it's basically the same) and pass a Value instance to the event listener.

In the HA event itself I'll add some more keys such as the device id and home id.

My preference goes to either 1 or 2.
Once we settle on this, I'll do the PR for the lib and continue with the core PR.

**Comment by MartinHjelmare** [comment]
Since the notification doesn't match all the properties of the `Value` class I think we should make a new dataclass.

**Comment by Nixon506E** [comment]
What is the status of getting scene notifications into home-assistant now that the value notifications are implemented? Is it just the need for a listener for these events?

**Comment by marcelveldt** [comment]
We needed to adjust a few things but the will be there within a few days.

**Comment by MartinHjelmare** [comment]
Closing this since the beta0 release is passed. We still have some things to fix, eg the lights.
