### ISSUE TITLE
Add commands to return node and network dumps

### ISSUE THREAD

**Issue by cgarwood** [home-assistant-libs/zwave-js-server-python#54]
Add commands to the lib to launch a new client session, grab a raw dump of the network or a specific node from zwave-js, and return the dump.

Output should match what the [zwave-js-server client](https://github.com/zwave-js/zwave-js-server/blob/master/src/bin/client.ts) outputs when dumping the network or a node.

**Comment by balloob** [comment]
I would suggest to not re-use the client class but instead open a WS connection. That way you're going to be able to access the raw data for the dump.

Logic for filtering nodes can be taken from Z-Wave JS Server:

https://github.com/zwave-js/zwave-js-server/blob/master/src/bin/client.ts#L35-L58
