### ISSUE TITLE
Update multicast support post S2 multicast implementation

### ISSUE THREAD

**Issue by mbbush** [home-assistant-libs/zwave-js-server-python#608]
ZWaveJS implemented S2 Multicast in https://github.com/zwave-js/node-zwave-js/pull/5475. This included some api changes, which this library needs to incorporate. 

See also https://github.com/home-assistant/core/issues/89569

**Comment by raman325** [comment]
the way we plan to implement this, HA and this lib will get it for free once it is supported in `zwave-js/zwave-js-server`. Support there is waiting on some additional features

**Comment by nmeachen** [comment]
@raman325: Is there an issue number tracking the work in zwave-js/zwave-js-server?

**Comment by raman325** [comment]
no, but feel free to open an issue there and close this one. I unfortunately can't transfer this issue between orgs otherwise  I would have just done that
