### ISSUE TITLE
Handle reconnect to Z-Wave JS server

### ISSUE THREAD

**Issue by balloob** [home-assistant-libs/zwave-js-server-python#66]
The client holds a `driver` object based on the initial received state. This object has listeners attached from Home Assistant.

When we reconnect, the client now holds a driver object that no longer represents the latest state. We don't deal with this case.

I can think of two options: 
 1. We throw away the `driver `object. Consumers of this lib will just have to re-initialize their stack + attach listeners. In the case of HA we would reload the config entry.
 2. We teach each model to update based on the latest state and add new events to indicate the consumer that they have to re-scan each model for latest data/values.

**Comment by MartinHjelmare** [comment]
1. makes most sense to me since the whole state is new. There's no value then to update models individually.

**Comment by balloob** [comment]
I agree. That way we know for sure everything is initialized correctly. 

For Home Assistant, we should add generic logic that if an entry is removed from the state machine and it is still registered in the entity registry, we write unavailable. That way this will go seamless.

**Comment by balloob** [comment]
Generic logic for HA: https://github.com/home-assistant/core/pull/45528

**Comment by marcelveldt** [comment]
Hmmm, this seems a bit complex when only a short hiccup of the connection occurs. I agree that we need some way to ensure we have the latest state but this feels a bit overly complex and, besides... why are we solving the reconnecting HA and not in the library ?

How I would do it:

If the connection is dropped and reconnected, simply ask the server for the full state again and loop through the values. 
We have the full state stored in the lib so we can very easily detect any changes.

Logic to mark the entity as unavailable when the connection is down is already down.

**Comment by marcelveldt** [comment]
But ofcourse there are two possible scenarios:

1) Connection to the WS server got dropped somehow and is reconnected. Only a short period of time and there are possible no or very few changes to process.
2) The whole WS server got reconnected. As the whole mesh is starting and interviewed there are many changes.
3) The whole WS server reconnects to a different (or factory resetted) stick, huge changes to process.

**Comment by balloob** [comment]
In all situations we already mark the integration as unavailable, restarting the integration wouldn't change anything for the user experience once https://github.com/home-assistant/core/pull/45528 is merged.

**Comment by MartinHjelmare** [comment]
This will be fixed by https://github.com/home-assistant-libs/zwave-js-server-python/pull/78 and connected changes in Home Assistant.
