### ISSUE TITLE
Fibaro FGRGBWM441 RGB controller no color wheel

### ISSUE THREAD

**Issue by thundergreen** [home-assistant-libs/zwave-js-server-python#95]
I dunno if this is the right place but apparently this controller is only partially supported. Instead of getting a color whel I get a light switch for each color. What do you need to debug or where do  I have to raise this issue?

**Comment by thundergreen** [comment]
additional info: I can control the color with the color switch which is not exposed to home assistant 

![image](https://user-images.githubusercontent.com/13320319/106861582-3db8a180-66c6-11eb-85d9-010f9e54894e.png)

**Comment by MartinHjelmare** [comment]
Please raise issues that are not specific to this library in the Home Assistant core repository. You can help us by creating a dump of your network and attaching it as a text file in the issue.

**Comment by scyto** [comment]
@thundergreen i did it for you, this is the right place for fibaro devices when using the new zwave js integration in hass https://github.com/home-assistant/core/issues/46138
